# Chaining this file to the main docker-compose file adds
# a default processing node instance. This is best for users
# who are just getting started with WebODM.

version: '2'
services:
  webapp:
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh broker:6379 -- /webodm/start.sh --create-default-pnode\""
    depends_on:
      - node-odm-1
  node-odm-1:
    image: opendronemap/node-opendronemap
    container_name: node-odm-1
    ports:
      - "3000"
